version: '3.8'

services:
  backend:
    build: ./server
    container_name: clothing_backend
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./server/conf/serviceAccountKey.json:/usr/src/app/conf/serviceAccountKey.json:ro

  frontend:
    build: ./client
    container_name: clothing_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
